# Site settings
title: Dan Shields
email: me@danshields.me
description: >
  I am become code, creator of worlds.
baseurl: ""
url: "http://danshields.me"
twitter_username: vedosity
github_username:  vedosity
keybase_username: vedosity

# Build settings
markdown: kramdown
permalink: pretty
include:
  - .well-known

# Disqus settings
category_ids:
  drafts: 3200431